services:
  tf:
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: tensorflow/tensorflow:1.5.0-gpu
    ports:
    - 8888:8888
    volumes:
    - .:/notebooks
    - nvidia_driver_384.90:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_384.90:
    external: true
